// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrdmzwoopmwhruxugmym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZG16d29vcG13aHJ1eHVnbXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjkzNTMsImV4cCI6MjA1ODcwNTM1M30.1ILdWos1ZXNe7wv73e6-M_5S7aGUzMOz9HaNQ8zg3Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);